### ISSUE TITLE
'Model' object has no attribute 'Enhance'

### ISSUE THREAD

**Issue by NhanDoremon** [joewybean/MMI-Det#4]
I am encountering this problem when running test.py
Can you you let me know how to fix it, thank you in advance.
![Capture](https://github.com/user-attachments/assets/432e23e5-1bab-47a1-bf20-e5fdeac15114)

**Comment by NhanDoremon** [comment]
Traceback (most recent call last):
  File "D:\OneDrive - Sejong University\NgheNhan_Master\Research\Facial Disguise Detection\Test Model\MMI-Det\test.py", line 339, in <module>
    test(opt.data,
  File "D:\OneDrive - Sejong University\NgheNhan_Master\Research\Facial Disguise Detection\Test Model\MMI-Det\test.py", line 123, in test
    out_all, Contrastive_Loss = model(img_rgb, img_ir, augment=augment)
  File "C:\Users\Nghe_Nhan\anaconda3\envs\MMI_Det\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Nghe_Nhan\anaconda3\envs\MMI_Det\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\OneDrive - Sejong University\NgheNhan_Master\Research\Facial Disguise Detection\Test Model\MMI-Det\models\yolo_test.py", line 160, in forward
    return self.forward_once(x, x2, profile)
  File "D:\OneDrive - Sejong University\NgheNhan_Master\Research\Facial Disguise Detection\Test Model\MMI-Det\models\yolo_test.py", line 187, in forward_once
    x = self.Enhance(x)  # CEM
  File "C:\Users\Nghe_Nhan\anaconda3\envs\MMI_Det\lib\site-packages\torch\nn\modules\module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'Model' object has no attribute 'Enhance'

**Comment by joewybean** [comment]
You can check the line 187 of model/yolo_test.py to see whether enchance module is applied properly.
